In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/student_level_math_data.csv")
df.head()

,city,state,median_income,student_teacher_ratio,free_lunch_pct,attendance_rate,parent_edu_index,math_score
0,San Antonio,TX,67354.577358,15.897744,0.030254,0.914193,0.480788,67.659738
1,Houston,TX,40187.667723,16.673495,0.174444,0.949323,0.350270,53.234517
2,Denver,CO,49460.214165,16.023684,0.269871,0.961709,0.650080,68.171228
3,Atlanta,GA,57189.608081,10.660766,0.103234,0.928179,0.550928,70.746257
4,Austin,TX,58352.092327,12.495852,0.168529,0.945500,0.553978,87.295248

In [2]:
city_df = (
    df.groupby(["city", "state"])
      .agg(
          avg_math_score=("math_score", "mean"),
          median_income=("median_income", "median"),
          student_teacher_ratio=("student_teacher_ratio", "mean"),
          free_lunch_pct=("free_lunch_pct", "mean"),
          attendance_rate=("attendance_rate", "mean"),
          parent_edu_index=("parent_edu_index", "mean"),
          student_count=("math_score", "count")
      )
      .reset_index()
)

city_df.head()

,city,state,avg_math_score,median_income,student_teacher_ratio,free_lunch_pct,attendance_rate,parent_edu_index,student_count
0,Atlanta,GA,68.463013,64945.246136,16.052506,0.282359,0.939668,0.600240,7971
1,Austin,TX,68.526386,64910.920387,16.022249,0.287204,0.939589,0.603094,7830
2,Boston,MA,68.484122,65073.945490,16.005836,0.288398,0.939466,0.598642,7914
3,Chicago,IL,68.436384,64895.184813,16.045360,0.281668,0.939778,0.600920,7895
4,Dallas,TX,68.517603,64642.317429,15.979351,0.284770,0.939425,0.602307,8034

In [3]:
print("Cities:", city_df.shape[0])
print("Columns:", city_df.shape[1])
print(city_df.describe(include="all"))

Cities: 15
Columns: 9
           city state  avg_math_score  median_income  student_teacher_ratio  \
count        15    15       15.000000      15.000000              15.000000
unique       15    10             NaN            NaN                    NaN
top     Atlanta    TX             NaN            NaN                    NaN
freq          1     4             NaN            NaN                    NaN
mean        NaN   NaN       68.471027   64962.657247              16.027966
std         NaN   NaN        0.091181     140.095948               0.030219
min         NaN   NaN       68.270721   64642.317429              15.979351
25%         NaN   NaN       68.432441   64899.318173              16.009011
50%         NaN   NaN       68.484122   64945.246136              16.025797
75%         NaN   NaN       68.524184   65020.345192              16.048933
max         NaN   NaN       68.604480   65250.393885              16.073322

        free_lunch_pct  attendance_rate  parent_edu_index  student_count
count        15.000000        15.000000         15.000000      15.000000
unique             NaN              NaN               NaN            NaN
top                NaN              NaN               NaN            NaN
freq               NaN              NaN               NaN            NaN
mean          0.284994         0.939596          0.600409    8000.000000
std           0.002837         0.000240          0.001681     105.129852
min           0.280860         0.939154          0.598062    7830.000000
25%           0.283328         0.939440          0.599188    7921.500000
50%           0.284335         0.939589          0.600116    7976.000000
75%           0.286758         0.939812          0.601850    8086.000000
max           0.291359         0.939937          0.603094    8176.000000

In [4]:
city_df.to_csv("../data/processed/city_level_math_performance.csv", index=False)
print("Saved: ../data/processed/city_level_math_performance.csv")

Saved: ../data/processed/city_level_math_performance.csv